### ISSUE TITLE
API 16 support

### ISSUE THREAD

**Issue by nehalshah50** [datatheorem/TrustKit-Android#13]
We have app with min SDK is at 16. Can this work with API 16?

**Comment by nabla-c0d3** [comment]
Yes - it will work in the following way:
* On API 16 devices, no pinning will be performed; the App will work as normal but the TrustKit functionality will be disabled.
* On API 17 and above, all the TrustKit functionality will be enabled.

**Comment by nehalshah50** [comment]
Do I then write custom cert pinning solution for API 16 to initialize the trust store based on supplied cert files and use it in the socket factory?

**Comment by nabla-c0d3** [comment]
You can do that, but doing pinning correctly is tricky. I would advise just giving up and not doing pinning at all for API 16 devices.

**Comment by nehalshah50** [comment]
Do we must have to use/configure reporting service? I looked at code i didn't see it being optional
