### ISSUE TITLE
New trust manager/sslsocketfactory each request??

### ISSUE THREAD

**Issue by nehalshah50** [datatheorem/TrustKit-Android#15]
Is it necessary to create a new PinningTrustManager/SSLSocketFactory for every request(TrustKit.getInstance().getSSLSocketFactory(url)? Can't we build the static map by host name in TrustKit and reuse?

**Comment by jobot0** [comment]
Sorry for the delay of the answer. Yes you need to specify the SSLSocketFactory for every new request. We haven't found any elegant way to do it dynamically and we have chosen to not manage the requests in TrustKit directly.
