### ISSUE TITLE
Multiple domain under domain-config

### ISSUE THREAD

**Issue by nehalshah50** [datatheorem/TrustKit-Android#16]
I have multiple domains under my domain config as both domain use the same certificates.  It looks like TurstKit configuration only takes the last one in the list and doesn't create multiple DomainPinningPolicy for each
`<domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="false">ABC.com</domain>
        <domain includeSubdomains="false">DEF.com</domain>
        <pin-set expiration="2018-09-10">
            <pin digest="SHA-256">xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</pin>
            <pin digest="SHA-256">yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy</pin>
        </pin-set>
</domain-config>`

**Comment by nabla-c0d3** [comment]
Hello, 
The `<pin-set>` tag should be under each `domain` tag.

**Comment by ocampoleandro** [comment]
I have tried that and got :

com.datatheorem.android.trustkit.config.ConfigurationException: Could not parse network security policy file.

xml

<domain includeSubdomains=“true”>url
      <pin-set>
        <pin digest=“SHA-256">asdasd>
        <pin digest=“SHA-256”>asdasda
      </pin-set>
    </domain>
<domain includeSubdomains=“true”>url2
      <pin-set>
        <pin digest=“SHA-256">asdasd>
        <pin digest=“SHA-256”>asdasda
      </pin-set>
    </domain>

Any idea about it?

**Comment by ocampoleandro** [comment]
Found the problem.
Each <domain> tag should be within a <domain-config>
