### ISSUE TITLE
Support for base-config

### ISSUE THREAD

**Issue by nehalshah50** [datatheorem/TrustKit-Android#17]
I have a situation where the server certificate doesn't exist in the default Android system trust store for Kitkat(API 19) and below. This is for the release build. So for that purpose we would need to build custom trust store. Can you add support for it using following configuration in the XML file? 
`<base-config>
        <trust-anchors>
            <certificates src="@raw/extracas"/>
            <certificates src="system"/>
        </trust-anchors>
 </base-config>`

**Comment by jobot0** [comment]
Sorry for the delay of the answer. TrustKit-Android doesn't have the goal to support all the features of the Network Security Configuration also we don't have any plan to support the `<base-config>` tag for now.
