### ISSUE TITLE
failed to connect on API 18 19

### ISSUE THREAD

**Issue by evollu** [datatheorem/TrustKit-Android#20]
I followed the readme and it works fine on API 20+
However I'm getting following error when trying with API 18 and 19.
`
javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb8a5a5c0: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure 
`

The call works when I use `sslSocketFactory(new TLSSocketFactory())`

**Comment by nabla-c0d3** [comment]
Hello, this seems to be a problem with Android and your application server, as TrustKit does not modify the SSL/TLS version used for the connections.

**Comment by evollu** [comment]
yeah look like it is caused by my server not supporting ssl v3
