### ISSUE TITLE
java.lang.IllegalStateException: TrustKit has already been initialized

### ISSUE THREAD

**Issue by evollu** [datatheorem/TrustKit-Android#21]
When app is closed though "back" button and resume, `onCreate` will be called again.
If I put `TrustKit.initializeWithNetworkSecurityConfiguration` inside onCreate as readme shows it throws `TrustKit has already been initialized` error.

shall I add a try catch around it to avoid the crash?

**Comment by jobot0** [comment]
Hey @evollu are you calling `Trustkit. initializeWithNetworkSecurityConfiguration` in the `onCreate` of your app or an activity? It should work if you use it inside the one of your application.
```java
public class MyApp extends Application {
  @Override
  public void onCreate() {
    Trustkit.initializeWithNetworkSecurityConfiguration(this);
  }
}
```

**Comment by evollu** [comment]
ah I'm calling it in Activity.

**Comment by Lynnette1** [comment]
Can you clarify this statement.

Hey @evollu are you calling Trustkit. initializeWithNetworkSecurityConfiguration in the onCreate of your app or an activity? It should work if you use it inside the one of your application.
