### ISSUE TITLE
Integration with React Native is broken

### ISSUE THREAD

**Issue by omerlh** [datatheorem/TrustKit-Android#26]
RN API was changed from version 43 (see this [commit](https://github.com/facebook/react-native/commit/0a71f48b1349ed09bcb6e76ba9ff8eb388518b15#diff-f8703d50cf5af4c06824e2928dddb500)). Since this change, there is no way to change the HTTP client used by RN to perform network request.
This [PR](https://github.com/facebook/react-native/pull/14068) should fix it.
This issue is mainly for documentation purpose, in case someone else will encounter this.
Thanks @AvivRubys for finding this.

**Comment by nabla-c0d3** [comment]
Thanks for letting us know! It sounds like there's not much to do on our side but wait for React Native to re-add the ability to customize the HTTP client?

**Comment by omerlh** [comment]
Yep, opened the issue mainly for documentation.

**Comment by tasarsu** [comment]
hi @omerlh did you find a certain solution for react native android ssl pinning?

**Comment by omerlh** [comment]
I think I might be missing something, but look like the original PR was closed without merging, and the PR it referred to is also closed...

**Comment by omerlh** [comment]
This is great news! I'll try that and update..
