### ISSUE TITLE
Not working in Android Kitkat

### ISSUE THREAD

**Issue by YogeshwarSharma** [datatheorem/TrustKit-Android#37]

**Comment by jobot0** [comment]
Hey @YogeshwarSharma thanks for testing the library. Could you give more details about your error ?

**Comment by YogeshwarSharma** [comment]
Hi,

I have integrated the trust kit and its working fine in Android N and above but not working in Android KitKat .

**Comment by jobot0** [comment]
The error could come from how the expiration date from the `pin-set` attribute is managed. Is it set to a "correct" date, meaning a date after today ?

**Comment by YogeshwarSharma** [comment]
Yes, Its set after today.
Actually, I am using the retrofit and passing the domain name to URL like below
            URL url = new URL("mydomain.com");
            String serverHostname = url.getHost();
            SSLSocketFactory socketFactory = TrustKit.getInstance().getSSLSocketFactory(serverHostname);
            builder.sslSocketFactory(socketFactory);

But this is not working in retrofit.

**Comment by jobot0** [comment]
Thanks I'm looking into it and let you know when I'm able to reproduce the bug. Could you give more information about the version of TrustKit-Android you're using and also the one for Retrofit ?

**Comment by YogeshwarSharma** [comment]
Trust kit version: 1.0.3
retrofit version:  2.0.2

**Comment by jobot0** [comment]
Hey @YogeshwarSharma sorry I'm still not able to reproduce your bug could you post your network_security_config here ?

**Comment by jobot0** [comment]
Hey @YogeshwarSharma have you resolved your issue ?

**Comment by YogeshwarSharma** [comment]
Ya, It has been resolved and that is not from your side.

**Comment by soumyamishra89** [comment]
@YogeshwarSharma can you tell me what issue you had and how did you solve it?
I am facing similar issue on android Kitkat.

**Comment by YogeshwarSharma** [comment]
@soumyamishra89 
Just mention only domains for which the certificate pinning should verify.
So, In network_security_config, Add the domains to include and with this change, certificate pinning will be only applicable to the mentioned domains
   <domain-config>
        *<domain includeSubdomains="true">google.com</domain>*
        
        <pin-set>
            <pin digest="SHA-256">key</pin>
            <pin digest="SHA-256">backupkey</pin>
        </pin-set>
        <trustkit-config enforcePinning="true" disableDefaultReportUri="true"/>
    </domain-config>
