### ISSUE TITLE
Include only specific domains

### ISSUE THREAD

**Issue by YogeshwarSharma** [datatheorem/TrustKit-Android#39]
Hi,

I am using multiple frameworks in my project like Firebase, Azure and other 3rd party servers.
So, I just want to include my server API domains for certificate pinning and Firebase, Azure and other 3rd party's API should be excluded. 

How we can achieve this in Android N and above as Its throwing exception for 3rd party  servers

**Comment by nabla-c0d3** [comment]
Hello,
You should just make sure the 3rd party servers/domains do not have any pinning configuration to keep the default behavior.

**Comment by YogeshwarSharma** [comment]
I just want to include specific domains for Trust Kit. How it can be achieved in Android N and above

**Comment by phuochau** [comment]
I have same problem as well, do we have any solution?
