### ISSUE TITLE
Not working on Android 19

### ISSUE THREAD

**Issue by soumyamishra89** [datatheorem/TrustKit-Android#47]
The trustkit setup works perfectly on Android 21 and above but it fails in Android 19.

here is my network-security config file:

`<network-security-config>
    <domain-config>
        <domain includeSubdomains="true">endpoint</domain> 
        <pin-set>
            <pin digest="SHA-256">hash1</pin>
            <pin digest="SHA-256">hash2</pin>
        </pin-set>
        <trustkit-config enforcePinning="true" />
    </domain-config>
</network-security-config>`

The issue is when a different pin hash is provided, it still allows connection.

**Comment by legion-zver** [comment]
Works only with certificates and if the flag is debug (look at the source code, there's a tremor)
