### ISSUE TITLE
How to use TrustKit with XHR (XMLHTTPREQUEST)

### ISSUE THREAD

**Issue by shubhamverma27** [datatheorem/TrustKit-Android#65]
Hi,
I am using trustkit with react native android and able to get it working with okhttp calls but when I use axios which use XHR, it results into a network error.
What could be the issue/ implementation for the same?
Thanks,

**Comment by shubhamverma27** [comment]
Sorry, I found the issue.
The issue is I am using 2 different domains.
How do I initialise the OkHttp object SSLSocketFactory for 2 different domain-configs?

**Comment by sureshbakshi** [comment]
@shubhamverma27 have you configured with AXIOS? if yes, please share the steps.

Thanks

**Comment by shubhamverma27** [comment]
You can follow the same setup as mentioned in the docs.
It will work for axios as well.

**Comment by shubhamdeol** [comment]
@shubhamverma27 which version of react native you are on?
For me app is crashing on start
