### ISSUE TITLE
DNS over HTTPS

### ISSUE THREAD

**Issue by yschimke** [datatheorem/TrustKit-Android#80]
Curious whether TrustKit is the right layer to enable features like OkHttp DNS over HTTPS support? It's hard to do anything like this in OkHttp directly, but there is a module supporting this in OkHttp.

https://github.com/square/okhttp/tree/master/okhttp-dnsoverhttps

n.b. I'm not an active user of this library, but mainly want to see additional adoption of DNS over HTTPS.  Please close if not relevant for the project.

**Comment by nabla-c0d3** [comment]
Hello,
TrustKit is not really responsible for DNS resolution; it only customizes certificate chain validation. Hence it's not a great place to implement and enable DNS over HTTPS. Unfortunately I don't think a lot of progress toward encrypted DNS resolution will happen until it is part the Android OS and enabled by default...
