### ISSUE TITLE
Migration required from JCenter

### ISSUE THREAD

**Issue by ecexplorer** [datatheorem/TrustKit-Android#81]
**Describe the bug**
JCenter will sunset new releases on Feb 28 and all usage on May 1. This means that TrustKit needs to remove its JCenter dependencies in this library (in Gradle) and distribute via Maven Central.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**To Reproduce**
Remove JCenter dependency from demo app, attempting to build says that datatheorem.trustkit cannot be located when gradle attempts to download dependencies.

**Expected behavior**
JCenter can be removed and Trustkit will still be available for download via Maven

**Additional context**
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by joshfriend** [comment]
I would recommend acting on this _immediately_ to claim the groupID on mavenCentral. The more time goes by, the likelier it is that someone will be looking to fix their broken builds and starts uploading the artifacts themselves. This may result in some messy ownership transfer hassle

https://central.sonatype.org/pages/choosing-your-coordinates.html

**Comment by nabla-c0d3** [comment]
Thanks everyone for the heads up. TrustKit has been migrated to Maven (https://github.com/datatheorem/TrustKit-Android/pull/86).
